from pydantic import BaseModel, Field
from enum import Enum

# We are defining a set of operations that we can perform on 
# the watchlist generated by AI
class WatchlistAction(str, Enum):
    "Valid watchlist operations"
    ADD = "add"
    REMOVE = "remove"
    LIST = "list"

# We are defining the structure in which we want our Watchlist 
# results to be displayed.
class WatchlistResult(BaseModel):
    "Structured result from watchlist operation"
    status: str = Field(description="Operation result: added, removed, listed, error")
    title: str | None = Field(default=None, description="Movie title acted upon")
    watchlist: list[str] = Field(default_factory=list, description="Current watchlist contents")
    count: int = Field(default=0, description="Number of items in watchlist")
    message: str | None = Field(default=None, description="Human-readable detail")

# We are defining the structure in which we want Guardrail 
# results to be diplayed 
class GuardrailResult(BaseModel):
    "Outcome of guardrail check"
    passed: bool = Field(description="Whether the check passed")
    reason: str | None = Field(default=None, description="Why it was blocked, if applicable")
    patterns_matched: list[str] = Field(default_factory=list, description="Patterns that triggered")
